from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime
from decimal import Decimal
from typing import Any

from pydantic import BaseModel, Field


class HeuristicFinding(BaseModel):
    """Finding generated by deterministic heuristics before LLM enrichment."""

    resource_id: str
    finding_type: str
    severity: str
    confidence: Decimal = Field(ge=0, le=1)
    estimated_savings: Decimal = Field(ge=0)
    recommended_action: str
    reason: str
    resource: dict[str, Any] = Field(default_factory=dict)


SAMPLE_FINDINGS: list[dict[str, Any]] = [
    {
        "finding_type": "zombie_subscription",
        "severity": "high",
        "confidence": 0.86,
        "estimated_savings": 129.0,
        "recommended_action": "Review owner and cancel or downgrade if no longer needed.",
        "reason": "The subscription has not been used for more than 30 days and costs over 50 per month.",
    },
    {
        "finding_type": "idle_resource",
        "severity": "medium",
        "confidence": 0.82,
        "estimated_savings": 185.0,
        "recommended_action": "Review workload owner and stop, schedule, or rightsize the instance.",
        "reason": "The cloud resource has CPU usage below 10 percent while costing over 100 per month.",
    },
]


def days_since(value: Any) -> int | None:
    if not value:
        return None
    if isinstance(value, datetime):
        dt = value
    elif isinstance(value, str):
        try:
            dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            return None
    else:
        return None

    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return max(0, (datetime.now(UTC) - dt).days)


def money(value: Any) -> Decimal:
    try:
        return Decimal(str(value or "0"))
    except Exception:
        return Decimal("0")


def severity_for_savings(savings: Decimal, confidence: Decimal) -> str:
    if savings >= Decimal("500") and confidence >= Decimal("0.80"):
        return "critical"
    if savings >= Decimal("150"):
        return "high"
    if savings >= Decimal("50"):
        return "medium"
    return "low"


def confidence_for_usage(usage_score: int, base: Decimal = Decimal("0.70")) -> Decimal:
    usage_gap = Decimal(max(0, 100 - usage_score)) / Decimal("100")
    return min(Decimal("0.95"), base + usage_gap * Decimal("0.20"))


def detect_zombie_subscription(record: dict[str, Any]) -> HeuristicFinding | None:
    inactive_days = days_since(record.get("last_used"))
    monthly_cost = money(record.get("monthly_cost"))
    if inactive_days is None or inactive_days <= 30 or monthly_cost <= Decimal("50"):
        return None

    confidence = min(Decimal("0.95"), Decimal("0.72") + Decimal(min(inactive_days, 90)) / Decimal("500"))
    return HeuristicFinding(
        resource_id=str(record["id"]),
        finding_type="zombie_subscription",
        severity=severity_for_savings(monthly_cost, confidence),
        confidence=confidence,
        estimated_savings=monthly_cost,
        recommended_action="Review owner and cancel, downgrade, or reclaim the subscription.",
        reason=f"No usage for {inactive_days} days while costing {monthly_cost} per month.",
        resource=record,
    )


def detect_unused_seat(record: dict[str, Any]) -> HeuristicFinding | None:
    usage_score = int(record.get("usage_score") or 0)
    resource_type = str(record.get("resource_type") or "")
    if "seat" not in resource_type and "user" not in resource_type:
        return None
    if usage_score >= 20:
        return None

    monthly_cost = money(record.get("monthly_cost"))
    confidence = confidence_for_usage(usage_score, Decimal("0.76"))
    return HeuristicFinding(
        resource_id=str(record["id"]),
        finding_type="unused_seats",
        severity=severity_for_savings(monthly_cost, confidence),
        confidence=confidence,
        estimated_savings=monthly_cost,
        recommended_action="Confirm ownership, then remove or suspend the unused seat.",
        reason=f"Seat-like resource has usage score {usage_score}, below the inactive threshold of 20.",
        resource=record,
    )


def detect_idle_resource(record: dict[str, Any]) -> HeuristicFinding | None:
    usage_score = int(record.get("usage_score") or 0)
    monthly_cost = money(record.get("monthly_cost"))
    resource_type = str(record.get("resource_type") or "")
    if "instance" not in resource_type and "resource" not in resource_type:
        return None
    if usage_score >= 10 or monthly_cost <= Decimal("100"):
        return None

    confidence = confidence_for_usage(usage_score, Decimal("0.78"))
    return HeuristicFinding(
        resource_id=str(record["id"]),
        finding_type="idle_resource",
        severity=severity_for_savings(monthly_cost, confidence),
        confidence=confidence,
        estimated_savings=monthly_cost,
        recommended_action="Review workload owner and stop, schedule, or rightsize this resource.",
        reason=f"Resource usage is {usage_score}, under 10, while monthly cost is {monthly_cost}.",
        resource=record,
    )


def detect_duplicate_tools(records: list[dict[str, Any]]) -> list[HeuristicFinding]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        key = str(record.get("resource_type") or "unknown").lower()
        grouped[key].append(record)

    findings: list[HeuristicFinding] = []
    for resource_type, group in grouped.items():
        providers = {str(item.get("provider") or item.get("tool_name") or "").split("-")[0] for item in group}
        if len(group) < 2 or len(providers) < 2:
            continue
        candidate = max(group, key=lambda item: money(item.get("monthly_cost")))
        savings = money(candidate.get("monthly_cost")) * Decimal("0.50")
        confidence = Decimal("0.62")
        findings.append(
            HeuristicFinding(
                resource_id=str(candidate["id"]),
                finding_type="duplicate_tool",
                severity=severity_for_savings(savings, confidence),
                confidence=confidence,
                estimated_savings=savings,
                recommended_action="Review overlapping tools and consolidate where ownership confirms redundancy.",
                reason=f"Multiple providers or tools appear in the same resource category: {resource_type}.",
                resource=candidate,
            )
        )
    return findings


def detect_cost_spikes(records: list[dict[str, Any]], threshold: Decimal = Decimal("0.35")) -> list[HeuristicFinding]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        grouped[str(record.get("tool_name") or record.get("id"))].append(record)

    findings: list[HeuristicFinding] = []
    for _, group in grouped.items():
        ordered = sorted(group, key=lambda item: str(item.get("snapshot_date") or ""))
        if len(ordered) < 2:
            continue
        previous = money(ordered[-2].get("monthly_cost"))
        current = money(ordered[-1].get("monthly_cost"))
        if previous <= 0:
            continue
        increase = (current - previous) / previous
        if increase <= threshold:
            continue
        savings = current - previous
        confidence = min(Decimal("0.90"), Decimal("0.65") + increase / Decimal("2"))
        findings.append(
            HeuristicFinding(
                resource_id=str(ordered[-1]["id"]),
                finding_type="cost_spike",
                severity=severity_for_savings(savings, confidence),
                confidence=confidence,
                estimated_savings=savings,
                recommended_action="Investigate recent usage, billing, or plan changes before taking action.",
                reason=f"Spend increased by {increase:.0%}, above the configured threshold of {threshold:.0%}.",
                resource=ordered[-1],
            )
        )
    return findings


def run_heuristics(records: list[dict[str, Any]]) -> list[HeuristicFinding]:
    findings: list[HeuristicFinding] = []
    for record in records:
        for detector in (detect_zombie_subscription, detect_unused_seat, detect_idle_resource):
            finding = detector(record)
            if finding:
                findings.append(finding)

    findings.extend(detect_duplicate_tools(records))
    findings.extend(detect_cost_spikes(records))
    return findings
